keys:
  - &bhunter age1wndy09nymnnma4zwskqapdzuaj663yage5qyustpqryyk6ue9qjsmf7hl0
creation_rules:
  - path_regex: hosts/.*\.yaml$
    key_groups:
      - age:
          - *bhunter
  - path_regex: modules/secrets\.yaml$
    key_groups:
      - age:
          - *bhunter
