[config]
reload_apps = false

[templates.base16]
input_path = "./theme/matugen/templates/base16.yaml"
output_path = "./theme/generated/base16.yaml"

[templates.colors]
input_path = "./theme/matugen/templates/colors.json"
output_path = "./theme/generated/colors.json"
